# Projeto de Análise de Vendas Superstore

## 1. Importação das Bibliotecas

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/projeto/SuperStoreOrders.csv')

## 2. Carregamento dos Dados

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

for raiz, pastas, arquivos in os.walk('/content/drive/MyDrive/Colab Notebooks/projeto/SuperStoreOrders.csv'):
    for arquivo in arquivos:
        if arquivo.endswith('.csv'):
            print(os.path.join(raiz, arquivo))

## 3. Análise Inicial

In [ ]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [ ]:
df.describe()

           quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [ ]:
df.shape

(51290, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [ ]:
df["sales"].head()

0    408
1    120
2     66
3     45
4    114
Name: sales, dtype: object

In [ ]:
df["sales"].sample(20)

4562        18
19232       56
32159       36
22602       82
10271      719
6721     1,983
14504       94
13545       61
48629      220
16956       47
2394        43
37628       58
48004    1,549
1738        38
31303       52
11959      130
32829       11
25073       26
36195    1,806
17712      856
Name: sales, dtype: object

In [ ]:
df["sales"].str.contains(",").sum()

np.int64(2630)

In [ ]:
df["sales"].apply(type).value_counts()

sales
<class 'int'>    51290
Name: count, dtype: int64

In [ ]:
df["sales"].sample(20).tolist()

[161,
 288,
 536,
 3,
 13,
 8,
 11,
 52,
 43,
 5,
 164,
 246,
 55,
 181,
 14,
 207,
 100,
 52,
 341,
 300]

In [ ]:
df["sales"].dtype

dtype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [ ]:
df.loc[
    df["sales"].astype(str).str.contains(","),
    "sales"
]

27       1,648
43       3,029
58       2,574
83       2,479
84       2,174
         ...
51151    1,831
51152    1,208
51228    1,264
51229    1,091
51231    1,049
Name: sales, Length: 2630, dtype: object

### Objetivo

Nesta etapa são realizadas verificações de qualidade dos dados, tratamento de tipos, conversão de datas e identificação de registros inconsistentes.

## 4. Limpeza e Tratamento

In [ ]:
df["sales"] = (
    df["sales"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

df["sales"] = pd.to_numeric(df["sales"])

In [ ]:
df["sales"].dtype

dtype('int64')

In [ ]:
df["ship_date"].head()

0    6/1/2011
1    8/1/2011
2    5/1/2011
3    5/1/2011
4    8/1/2011
Name: ship_date, dtype: object

In [ ]:
df["order_date"].head()

0    1/1/2011
1    1/1/2011
2    1/1/2011
3    1/1/2011
4    1/1/2011
Name: order_date, dtype: object

In [ ]:
df["order_date"].sample(20).tolist()

['6/5/2014',
 '9/6/2014',
 '26-11-2011',
 '3/3/2014',
 '4/10/2011',
 '10/8/2013',
 '18-06-2013',
 '9/3/2012',
 '15-03-2014',
 '23-11-2011',
 '14-01-2013',
 '4/9/2014',
 '7/11/2014',
 '5/12/2014',
 '24-02-2014',
 '29-09-2011',
 '23-04-2011',
 '13-02-2013',
 '5/11/2014',
 '25-02-2014']

In [ ]:
df["order_date"].astype(str).sample(20).tolist()

['12/5/2014',
 '7/10/2014',
 '24-04-2014',
 '7/7/2014',
 '21-09-2014',
 '17-10-2012',
 '29-10-2013',
 '1/12/2012',
 '23-12-2013',
 '21-09-2013',
 '13-08-2014',
 '28-07-2014',
 '17-11-2014',
 '15-12-2011',
 '6/6/2014',
 '26-12-2012',
 '27-04-2013',
 '28-07-2011',
 '15-02-2012',
 '14-09-2013']

In [ ]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="mixed",
    dayfirst=True
)

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="mixed",
    dayfirst=True
)

In [ ]:
df[["order_date", "ship_date"]].head()

  order_date  ship_date
0 2011-01-01 2011-01-06
1 2011-01-01 2011-01-08
2 2011-01-01 2011-01-05
3 2011-01-01 2011-01-05
4 2011-01-01 2011-01-08

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  datetime64[ns]
 2   ship_date       51290 non-null  datetime64[ns]
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 8.2+ MB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isna().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
delivery_days     0
dtype: int64

In [ ]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,delivery_days
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011,5
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011,7
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011,4
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011,4
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011,7

In [ ]:
(df["profit"]<0).sum()

np.int64(12543)

In [ ]:
((df["profit"]<0).mean()*100).round(2)

np.float64(24.46)

In [ ]:
df.loc[
    df["profit"] < 0,
    ["sales", "discount", "profit"]
].head(20)

    sales  discount     profit
3      45      0.50   -26.0550
8     912      0.40  -319.4640
10    338      0.45  -122.8005
11    211      0.55   -70.3995
14    159      0.40   -95.6760
18     69      0.40   -26.4120
19    135      0.47   -45.9018
33     74      0.60  -107.8560
37     27      0.50   -21.9000
40     17      0.50    -1.0500
46    273      0.20   -64.7748
49      4      0.80    -5.4870
53     41      0.47   -27.0942
62    445      0.25  -136.7100
63    274      0.45   -44.8380
76     27      0.45    -4.4940
82      5      0.50    -0.1050
85    987      0.60 -1011.6360
87     77      0.60   -53.7096
89    116      0.50   -55.6500

In [ ]:
df.sort_values("profit").head(10)[
    ["sales", "profit", "discount", "shipping_cost", "category", "sub_category"]
]

       sales     profit  discount  shipping_cost         category sub_category
31884   4500 -6599.9780       0.7         451.63       Technology     Machines
29212   3085 -4088.3760       0.6          51.89       Technology       Phones
47195   8000 -3839.9904       0.5         674.82       Technology     Machines
3775    2178 -3701.8928       0.8         172.07  Office Supplies      Binders
37130   2550 -3399.9800       0.7         120.31       Technology     Machines
24286   3400 -3059.8200       0.5         286.87  Office Supplies   Appliances
28510   3499 -3009.4350       0.5         333.10       Technology       Phones
49628   1890 -2929.4845       0.8         129.51  Office Supplies      Binders
34513   2171 -2750.2800       0.7         390.09        Furniture       Tables
19251   1800 -2639.9912       0.7         219.62       Technology     Machines

In [ ]:
round(df["shipping_cost"].mean(), 2)

np.float64(26.38)

In [ ]:
round(df[df["profit"] < 0]["shipping_cost"].mean(),2)

np.float64(21.16)

### Objetivo

Criação de métricas derivadas para apoiar análises de rentabilidade e desempenho logístico.

## 5. Engenharia de Atributos

In [ ]:
df["profit_margin"] = (
    df["profit"] / df["sales"]
) * 100

In [ ]:
df.sort_values("profit_margin").head(20)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,delivery_days,profit_margin
40017,US-2014-102288,2014-06-20,2014-06-24,Standard Class,Zuschuss Carroll,Consumer,Texas,United States,US,Central,...,Hoover Replacement Belt for Commercial Guardsm...,0,1,0.80,-1.1100,0.01,Medium,2014,4,-inf
18023,IT-2012-5588535,2012-11-16,2012-11-21,Standard Class,Mitch Willingham,Corporate,Lower Saxony,Germany,EU,Central,...,"Chromcraft Coffee Table, Fully Assembled",242,6,0.85,-1144.1160,23.38,High,2012,5,-472.775207
11874,ID-2012-56913,2012-05-23,2012-05-30,Standard Class,Barry Gonzalez,Consumer,Khyber Pakhtunkhwa,Pakistan,APAC,Central Asia,...,"Hon Coffee Table, Fully Assembled",63,1,0.80,-244.3860,6.07,Low,2012,7,-387.914286
9369,IT-2012-2732419,2012-01-20,2012-01-24,Standard Class,Nicole Brennan,Corporate,England,United Kingdom,EU,North,...,"Deflect-O Clock, Black",70,7,0.80,-271.2360,10.74,High,2012,4,-387.480000
2235,ID-2011-13436,2011-05-18,2011-05-23,Standard Class,Guy Phonely,Corporate,Punjab,Pakistan,APAC,Central Asia,...,"Hon Coffee Table, Fully Assembled",127,2,0.80,-488.7720,14.94,High,2011,5,-384.859843
50062,CA-2014-165099,2014-12-12,2014-12-14,First Class,Dennis Kane,Consumer,Texas,United States,US,Central,...,Hoover Commercial Lightweight Upright Vacuum,1,2,0.80,-3.7584,0.14,High,2014,2,-375.840000
22273,ID-2013-10713,2013-04-09,2013-04-13,Standard Class,Tanja Norvell,Home Office,Sindh,Pakistan,APAC,Central Asia,...,"Lesro Training Table, Adjustable Height",108,2,0.80,-390.2640,9.62,Medium,2013,4,-361.355556
12082,IT-2012-2675422,2012-05-31,2012-06-02,Second Class,Benjamin Farhat,Home Office,Lower Saxony,Germany,EU,Central,...,"Bevis Conference Table, Fully Assembled",555,4,0.85,-1924.5420,62.75,High,2012,2,-346.764324
23362,ID-2013-34177,2013-05-16,2013-05-22,Standard Class,Berenike Kampe,Consumer,Ulsan,South Korea,APAC,North Asia,...,"Lesro Coffee Table, Rectangular",100,2,0.80,-344.4120,7.72,Medium,2013,6,-344.412000
4769,ID-2011-55849,2011-08-31,2011-09-04,Standard Class,Bruce Geld,Consumer,Punjab,Pakistan,APAC,Central Asia,...,"Chromcraft Round Table, Fully Assembled",375,4,0.80,-1218.3840,0.25,Medium,2011,4,-324.902400
7814,CA-2011-101147,2011-12-02,2011-12-04,First Class,Matt Collins,Consumer,Illinois,United States,US,Central,...,Staples,2,1,0.80,-6.3441,0.23,High,2011,2,-317.205000
21445,CA-2013-110898,2013-03-07,2013-03-13,Standard Class,Lena Cacioppo,Consumer,Illinois,United States,US,Central,...,Commercial WindTunnel Clean Air Upright Vacuum...,2,3,0.80,-6.3018,0.16,Medium,2013,6,-315.090000
29620,NI-2013-4420,2013-10-04,2013-10-10,Standard Class,Michael Paige,Corporate,Lagos,Nigeria,Africa,Africa,...,"Avery Hole Reinforcements, Economy",1,1,0.70,-3.0870,0.06,Medium,2013,6,-308.700000
32676,US-2013-131114,2013-12-10,2013-12-14,Second Class,Rob Williams,Corporate,Illinois,United States,US,Central,...,Belkin 6 Outlet Metallic Surge Strip,4,2,0.80,-11.7612,0.56,Medium,2013,4,-294.030000
6203,CA-2011-163748,2011-10-14,2011-10-18,Standard Class,Hunter Glantz,Consumer,Texas,United States,US,Central,...,Hoover Replacement Belts For Soft Guard & Comm...,3,4,0.80,-8.5320,0.33,High,2011,4,-284.400000
12415,CA-2012-164007,2012-06-08,2012-06-12,Standard Class,Maureen Gnade,Consumer,Illinois,United States,US,Central,...,Hoover Shoulder Vac Commercial Portable Vacuum,143,2,0.80,-393.6020,1.56,Medium,2012,4,-275.246154
47945,US-2014-124926,2014-11-14,2014-11-19,Second Class,Maria Etezadi,Home Office,Texas,United States,US,Central,...,Hoover Commercial Soft Guard Upright Vacuum An...,9,6,0.80,-24.7086,2.17,High,2014,5,-274.540000
22969,CA-2013-163398,2013-05-04,2013-05-09,Standard Class,Christy Brittain,Consumer,Illinois,United States,US,Central,...,Acco Smartsocket Color-Coded Six-Outlet AC Ada...,26,3,0.80,-71.2962,1.17,Medium,2013,5,-274.216154
33860,CA-2014-147207,2014-01-03,2014-01-05,Second Class,Trudy Schmidt,Consumer,Texas,United States,US,Central,...,Hoover Commercial SteamVac,5,2,0.80,-13.5800,0.88,High,2014,2,-271.600000
50399,US-2014-116701,2014-12-18,2014-12-22,Second Class,Logan Currie,Consumer,Texas,United States,US,Central,...,Eureka Sanitaire Commercial Upright,66,2,0.80,-178.9668,3.63,Medium,2014,4,-271.161818

In [ ]:
df["delivery_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [ ]:
df["delivery_days"].describe()

count    51290.000000
mean         3.969370
std          1.729437
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: delivery_days, dtype: float64

In [ ]:
df[df["delivery_days"] == 0].head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,delivery_days,profit_margin
7,IN-2011-79397,2011-01-03,2011-01-03,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,"Hoover Microwave, White",276,1,0.1,110.412,125.32,Critical,2011,0,40.004348
20,IN-2011-79397,2011-01-03,2011-01-03,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,"Avery Color Coded Labels, Laser Printer Compat...",36,3,0.1,4.743,7.46,Critical,2011,0,13.175000
73,MX-2011-135629,2011-01-07,2011-01-07,Same Day,Dorothy Dickinson,Consumer,São Paulo,Brazil,LATAM,South,...,"Stockwell Rubber Bands, Bulk Pack",43,4,0.0,6.000,3.94,High,2011,0,13.953488
74,MX-2011-135629,2011-01-07,2011-01-07,Same Day,Dorothy Dickinson,Consumer,São Paulo,Brazil,LATAM,South,...,"Ibico Index Tab, Durable",19,3,0.0,2.400,3.69,High,2011,0,12.631579
101,HU-2011-1380,2011-01-10,2011-01-10,Same Day,Elpida Rittenbach,Corporate,Budapest,Hungary,EMEA,EMEA,...,"Ikea Library with Doors, Traditional",363,1,0.0,159.870,134.59,Critical,2011,0,44.041322

In [ ]:
(df["delivery_days"] == 0).sum()

np.int64(2600)

### Objetivo

Identificar padrões de vendas, distribuição de clientes e comportamento dos mercados atendidos.

## 6. Análise Exploratória

In [ ]:
df["category"].value_counts()

df["segment"].value_counts()

df["market"].value_counts()

df["region"].value_counts()

region
Central           11117
South              6645
EMEA               5029
North              4785
Africa             4587
Oceania            3487
West               3203
Southeast Asia     3129
East               2848
North Asia         2338
Central Asia       2048
Caribbean          1690
Canada              384
Name: count, dtype: int64

In [ ]:
df["category"].value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [ ]:
df["segment"].value_counts()

segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [ ]:
df["market"].value_counts()

market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

## 7. Exportação dos Dados Tratados

In [ ]:
df.to_csv(
    "superstore_tratado.csv",
    index=False
)

In [ ]:
from google.colab import files

df.to_csv("superstore_tratado.csv", index=False)

files.download("superstore_tratado.csv")